# docker-compose.yml
image: node:18
working_dir: /app
volumes:
- ./app:/app
command: ["npm", "start"]
ports:
- "4000:4000"
db:
image: mariadb:10.6
environment:
MYSQL_ROOT_PASSWORD: root
MYSQL_DATABASE: experiment
ports:
- "3306:3306"